In [3]:
import numpy  as np
import pandas as pd

In [4]:
sales = pd.DataFrame({
    "OrderID":[101,102,103,104,105,106],
    "Customer":["Sankara","Priya","Rohit","Sneha","Rahul","Neha"],
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi","Mumbai"],
    "Category":["Laptop","Phone","Tablet","Laptop","Phone","Tablet"],
    "Quantity":[2,1,3,1,2,5],
    "Price":[75000,45000,30000,80000,50000,25000]
})

sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [5]:
# Question 1
# Display only Customer and Category.

# Question 2
# Find all Phone orders.

# Question 3
# Find all orders from Delhi.

# Question 4
# Display the first three rows.

# Question 5
# How many rows and columns are present?

In [11]:
sales[['Customer', 'Category']]

  Customer Category
0  Sankara   Laptop
1    Priya    Phone
2    Rohit   Tablet
3    Sneha   Laptop
4    Rahul    Phone
5     Neha   Tablet

In [13]:
sales[sales['Category'] == 'Phone']

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
4      105    Rahul   Delhi    Phone         2  50000

In [14]:
sales[sales['City'] == 'Delhi']

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
2      103    Rohit  Delhi   Tablet         3  30000
4      105    Rahul  Delhi    Phone         2  50000

In [15]:
sales.head(3)

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000

In [17]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   6 non-null      int64
 1   Customer  6 non-null      object
 2   City      6 non-null      object
 3   Category  6 non-null      object
 4   Quantity  6 non-null      int64
 5   Price     6 non-null      int64
dtypes: int64(3), object(3)
memory usage: 420.0+ bytes

In [19]:
sales.shape

(6, 6)

In [20]:
sales = pd.DataFrame({
    "OrderID": [101,102,103,104,105,106,107,108],
    "Customer": ["Sankara","Priya","Rahul","Sneha","Priya","Rahul","Sankara","Neha"],
    "City": ["Delhi","Mumbai","Delhi","Pune","Mumbai","Delhi","Delhi","Pune"],
    "Category": ["Laptop","Phone","Phone","Laptop","Tablet","Laptop","Tablet","Phone"],
    "Amount": [80000,50000,35000,90000,25000,85000,30000,45000]
})

sales

   OrderID Customer    City Category  Amount
0      101  Sankara   Delhi   Laptop   80000
1      102    Priya  Mumbai    Phone   50000
2      103    Rahul   Delhi    Phone   35000
3      104    Sneha    Pune   Laptop   90000
4      105    Priya  Mumbai   Tablet   25000
5      106    Rahul   Delhi   Laptop   85000
6      107  Sankara   Delhi   Tablet   30000
7      108     Neha    Pune    Phone   45000

In [21]:
# Question 1
# Find the total sales (Amount) for each city.
sales.groupby('City')['Amount'].sum()

City
Delhi     230000
Mumbai     75000
Pune      135000
Name: Amount, dtype: int64

In [22]:
# Question 3 (Multiple Aggregations)
# For each city, find:
# Total Sales
# Average Sales
# Maximum Sales
# Number of Orders
sales.groupby('City')['Amount'].agg(['sum', 'mean', 'max', 'count'])

           sum     mean    max  count
City
Delhi   230000  57500.0  85000      4
Mumbai   75000  37500.0  50000      2
Pune    135000  67500.0  90000      2

In [ ]:
import pandas as pd

customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Sankara", "Priya", "Rahul", "Sneha"],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 3, 5],
    "Amount": [5000, 7000, 9000, 6000]
})

In [25]:
orders

   OrderID  CustomerID  Amount
0      101           1    5000
1      102           2    7000
2      103           3    9000
3      104           5    6000
4      105           2    8000

In [26]:
customers

   CustomerID CustomerName    City
0           1      Sankara   Delhi
1           2        Priya  Mumbai
2           3        Rahul   Delhi
3           4        Sneha    Pune